Use standart functions for ostream conversions
forGGe/theCore pull request #313
Opened 2017-10-27 20:54 UTC by hoip

2017-10-27 21:11 UTC, forGGe commented
Related to #204

2017-10-27 21:12 UTC, forGGe requested changes
Looks good, only minor nitpicks.

Also, please squash all commits together with some meaningful message, like
`>204 Use standart functions for ostream conversions`

See also:
https://forgge.github.io/theCore/community.html#commit-and-pr-style , Rule 3.

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> +    template< typename stream >
Move `endl` where it was - 4 spaces left.

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> + #include <ecl/assert.h>
Add space here.

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> + #ifndef ECL_OSTREAM_HPP
Let's preserve an indentation. Remove 1 space indent from whole file

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> +    char n = snprintf(buff, sizeof(buff), "%c", character);
No need to write character in buffer and then put it in the device. Let's just call `put()` here.

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> +     while (string[i] != '\0')
According to the code style - place brackets on 1st line of `while` and similar statements.
See Rule 1. in https://forgge.github.io/theCore/community.html#bracket-placement

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> +             //Serial.printlnf("\n>%d<\n", count);
This line can be deleted.
See Rule 1. https://forgge.github.io/theCore/community.html#comments

2017-10-27 21:12 UTC, forGGe commented on lib/cpp/export/ecl/ostream.hpp
> +     char buff [32];
No need to write character in buffer and then put it in the device. Previous version of this function was good, let's bring it back.

2017-11-05 23:39 UTC, forGGe approved these changes

2017-11-05 23:40 UTC, forGGe commented
Changes are approved, but hoip/theCore#1 should be merged first.

2017-11-06 21:00 UTC, merged

2017-11-06 21:00 UTC, forGGe commented
Merged. Thanks @hoip !

2017-11-06 22:42 UTC, hoip commented
Please!